# Generated by Django 5.1.5 on 2025-01-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='edition',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='livre',
            name='genre',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
        migrations.AddField(
            model_name='livre',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
    ]
