# Generated by Django 5.1.5 on 2025-01-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_livre_edition_livre_genre_livre_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='edition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livre',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='livre',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
    ]
