# Generated by Django 5.1.5 on 2025-01-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_livre_edition_alter_livre_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='couverture',
            field=models.ImageField(blank=True, null=True, upload_to='couvertures/'),
        ),
    ]
